services:
  pokemon-assistant:
    container_name: Showdown_Battle_Assistant
    image: crc8109/pokemon-assistant:latest  # Use the pushed image
    ports:
      - "8501:8501"
    restart: unless-stopped
